### ISSUE TITLE
Card don't respond

### ISSUE THREAD

**Issue by PrzemekSkw** [mikevanes/spotify-card-v2#16]
**Describe the bug**
I cannot choose any option, card don't see any devices.

* [X] Reproducable on a plain lovelace panel without card, style or theme mods
* [X] Using latest version of spotcast and spotify-card-v2 [ ]
* [X] Using latest stable version of Home Assistant
* [X] I have Spotify Premium
* [X] I have setup the Spotify integration in Home Assistant

**To Reproduce**
1. Creat new dashboard
2. Add spotify-card-2
3. Try to select someting
4. Nothing happen, card is loading and don't see any player.

**Expected behavior**
I expect card will work and allow me to play media like Media Tab in HA

**Screenshots**
![image](https://github.com/user-attachments/assets/65619a62-30d3-4ca0-b214-6324436eb957)

**Environment (please complete the following information):**
 - OS: [UnraidOS]
 - Browser: [Brave]
 - Version: [Wersja 1.73.97 Chromium: 131.0.6778.108]
 - HA version: [2024.12.0 ]
 - spotcast version: [ 4.0.0]

**Configuration**
Logs from HA:
```
Detected that custom integration 'spotcast' calls `async_add_job`, which should be reviewed against https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/spotcast/__init__.py, line 154: hass.async_add_job(get_devices()). This will stop working in Home Assistant 2025.4, please create a bug report at https://github.com/fondberg/spotcast/issues
Detected that custom integration 'spotcast' calls `async_add_job`, which should be reviewed against https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/spotcast/__init__.py, line 172: hass.async_add_job(get_player()). This will stop working in Home Assistant 2025.4, please create a bug report at https://github.com/fondberg/spotcast/issues
Detected that custom integration 'spotcast' calls `async_add_job`, which should be reviewed against https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/spotcast/__init__.py, line 134: hass.async_add_job(get_playlist()). This will stop working in Home Assistant 2025.4, please create a bug report at https://github.com/fondberg/spotcast/issues
```
The same situation I have when I try spotify-card from HACS.
Regards

**Comment by pr0fetul** [comment]
Hi,
I have the exact same situation. Latest HA version
Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7, 
latest release of spotify-card-v2.

Adding the card to the dashboard results in:
![image](https://github.com/user-attachments/assets/7070dece-5e61-402f-bf85-72857a1fcd0c)

If I use the Spotcast service to play media on one of the speakers - it works - the content is played, the card shows what's playing but no device:
![image](https://github.com/user-attachments/assets/1ff789a3-8657-4506-8d2f-e49bab88df29)

![image](https://github.com/user-attachments/assets/475a67b1-f8e8-4c6e-906a-5d976c4ee736)


Any idea on what can be done to make it work?

Thank you

**Comment by VicenteKER** [comment]
Same here....

**Comment by andyrowe247** [comment]
Same issue with my installation.

**Comment by mattred33** [comment]
Also having the same issue. I just installed this v2 yesterday, so it hasn't worked for me yet.

**Comment by JOHLC** [comment]
Having the same issue here. In my web browser's dev console, I am seeing these errors:
 
```
2services.js:31  Uncaught (in promise) TypeError: this.chromecast_devices.filter is not a function
    at Qe.getFilteredDevices (services.js:31:82)
    at Qe.generateDeviceList (services.js:31:82)
    at Qe.render (services.js:31:82)
    at Qe.update (spotify-card.js?hacstag=173955605240:186:1183)
    at Qe.performUpdate (spotify-card.js?hacstag=173955605240:148:6614)
    at Qe._enqueueUpdate (spotify-card.js?hacstag=173955605240:148:6302)
index.m.js:1  Uncaught (in promise) Error: Failed to fetch playlists: [object Object]
    at Re.fetchPlaylists (index.m.js:1:4274)
    at async entities.js:28:83
index.m.js:1  Uncaught (in promise) Error: Failed to fetch playlists: [object Object]
    at Re.fetchPlaylists (index.m.js:1:4274)
    at async entities.js:28:83
```

Also these in Home Assistant
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:315
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:58:23 PM (983 occurrences)
Last logged: 11:20:15 PM

[139665521828640] Error handling message: extra keys not allowed @ data['playlist_type']. Got 'default' required key not provided @ data['category']. Got None (invalid_format) User from my.ip.addre.ss (my user / browser string e.g Mozilla/5.0)
[139665521828640] Error handling message: extra keys not allowed @ data['playlist_type']. Got '' required key not provided @ data['category']. Got None (invalid_format) User from my.ip.addre.ss (my user / browser string e.g Mozilla/5.0)
[139666670511888] Error handling message: extra keys not allowed @ data['playlist_type']. Got '' required key not provided @ data['category']. Got None (invalid_format) User from my.ip.addre.ss (my user / browser string e.g Mozilla/5.0)
[139666670511888] Error handling message: extra keys not allowed @ data['playlist_type']. Got 'default' required key not provided @ data['category']. Got None (invalid_format) User from my.ip.addre.ss (my user / browser string e.g Mozilla/5.0)
[139663887231024] Error handling message: extra keys not allowed @ data['playlist_type']. Got 'default' required key not provided @ data['category']. Got None (invalid_format) User from my.ip.addre.ss (my user / browser string e.g Mozilla/5.0)
```
 
 I have completely rebuilt my config for my account, Home Assistant integration, Spotcast, and the card and everything is working fine except for the card. 
 
 
![image](https://github.com/user-attachments/assets/020547a7-ba2c-4d97-b122-2146c12b775c)

**Comment by mikevanes** [comment]
Version 5 of spotcast is not supported. This is a complete rewrite of spotcast. I am working on a new card to fix this. Hopefully it will release somewhere next week.

**Comment by mikevanes** [comment]
In the meantime you can try to install this card: https://github.com/mikevanes/spotcast-spotify-card it is undergoing heavy development and is not in a release-ready state at all. Nothing is configurable, but the default account should be able to select some playlists.
